README.md, src/main/java/org/hiero/sketch/spreadsheet/HeapTopK.java, src/main/java/org/hiero/sketch/spreadsheet/ITopK.java, src/main/java/org/hiero/sketch/spreadsheet/TreeTopK.java, src/test/java/org/hiero/sketch/HeapTopKTest.java, src/test/java/org/hiero/sketch/MyCompare.java, src/test/java/org/hiero/sketch/SortedTreeTest.java, src/test/java/org/hiero/sketch/TreeTopKTest.java
Two implementations:
HeapTopK uses a HashMap
TreeTopK used a TreeMap.
=> Implementation fo TopK interface

src/main/java/org/hiero/sketch/spreadsheet/Bucket.java, src/main/java/org/hiero/sketch/spreadsheet/IHistogram.java, src/main/java/org/hiero/sketch/table/FullMembership.java, src/main/java/org/hiero/sketch/table/LazyMembership.java, src/main/java/org/hiero/sketch/table/SparseMembership.java, src/main/java/org/hiero/sketch/table/api/IMembershipSet.java, src/main/java/org/hiero/utils/IntSet.java, src/test/java/org/hiero/sketch/BucketTest.java, src/test/java/org/hiero/sketch/MembershipTest.java
I made the two changes you requested plus modified the sample methods in sparseMembership in the nice way you did in lazyMembership. I also added a bucket class as preparation for histogram plus test for it. You can ignore the interface for histogram, it is an initial thought.
=> code cleaning of indexing plus bucket

src/main/java/org/hiero/sketch/spreadsheet/Bucket.java, src/main/java/org/hiero/sketch/spreadsheet/BucketSetDescription.java, src/main/java/org/hiero/sketch/spreadsheet/Histogram1D.java, src/main/java/org/hiero/sketch/spreadsheet/IHistogram.java, src/main/java/org/hiero/sketch/table/LazyMembership.java, src/main/java/org/hiero/sketch/table/SparseMembership.java, src/main/java/org/hiero/utils/IntSet.java, src/test/java/org/hiero/sketch/BucketTest.java, src/test/java/org/hiero/sketch/MembershipTest.java
I began the Histogram1D. Take a look if this is what you were thinking of. If yes, I'll continue implementing a one dimensional histogram based on sampling. I'm thinking of writing a method  that continues to sample more and more data until it reaches the error bars specified by the user (a.la the paper we discussed a while ago).
=> Changed the iterator as we discussed plus 1dhistogram

hieroplatform/pom.xml
=> Remove spurious dependency from pom.xml

hieroplatform/hieroplatform.iml, hieroplatform/pom.xml, hieroplatform/src/main/java/org/hiero/sketch/dataset/api/package-info.java, hieroplatform/src/main/java/org/hiero/sketch/dataset/package-info.java, hieroplatform/src/main/java/org/hiero/sketch/remoting/package-info.java, hieroplatform/src/main/java/org/hiero/sketch/spreadsheet/package-info.java, hieroplatform/src/main/java/org/hiero/sketch/storage/package-info.java, hieroplatform/src/main/java/org/hiero/sketch/table/api/package-info.java, hieroplatform/src/main/java/org/hiero/sketch/table/package-info.java, hieroplatform/src/main/java/org/hiero/utils/FieldsAreNonnullByDefault.java, hieroplatform/src/main/java/org/hiero/utils/MethodsAreNonnullByDefault.java, hieroplatform/src/main/java/org/hiero/utils/package-info.java
I still don't fail the build on this, given the number of warnings being reported.
=> All fields, methods and parameters are now Nonnull by default.

hieroplatform/src/main/java/org/hiero/table/FullMembership.java, hieroplatform/src/main/java/org/hiero/table/api/IMembershipSet.java, hieroplatform/src/main/java/org/hiero/utils/HashUtil.java, hieroplatform/src/main/java/org/hiero/utils/IntArrayGenerator.java, hieroplatform/src/main/java/org/hiero/utils/IntSet.java, hieroplatform/src/main/java/org/hiero/utils/Randomness.java, hieroplatform/src/main/java/org/hiero/utils/TestTables.java, hieroplatform/src/test/java/org/hiero/sketch/HeapTopKTest.java, hieroplatform/src/test/java/org/hiero/sketch/ListComparatorTest.java, hieroplatform/src/test/java/org/hiero/sketch/MonoidTopKTest.java, hieroplatform/src/test/java/org/hiero/sketch/PercentileTest.java, hieroplatform/src/test/java/org/hiero/sketch/RandomnessTest.java, hieroplatform/src/test/java/org/hiero/sketch/TestUtil.java, hieroplatform/src/test/java/org/hiero/sketch/TreeTopKTest.java, hieroplatform/src/test/java/org/hiero/sketch/TreeVsHeapTest.java
Adding the wrapper for more functions in Randomness API
=> Adding the missing functions for Randomness

hieroweb/src/main/webapp/hiero.css, hieroweb/src/main/webapp/histogram.ts, hieroweb/src/main/webapp/index.html, hieroweb/src/main/webapp/initialObject.ts, hieroweb/src/main/webapp/ui.ts
This makes a back button less necessary.
=> Open new views in the same web page

.gitignore, web/src/main/webapp/heatMap.ts, web/src/main/webapp/hillview.css, web/src/main/webapp/histogram.ts, web/src/main/webapp/histogram2d.ts, web/src/main/webapp/menu.ts, web/src/main/webapp/table.ts
The context menu is now created dynamically and there can be only one.
Note: 3rd attempt. I'm in the organization now so it should be fine.
=> Fixed the issues we had with the menus. Also, changed table/menu fonts to sans-serif (easier for the eyes).

data/On_Time.schema, deployment/config.yaml, deployment/demo-data-cleaner.yaml, deployment/demo-prepare.yaml, deployment/prepare.yaml, deployment/start.yaml, platform/src/main/java/org/hillview/dataset/RemoteDataSet.java, platform/src/main/java/org/hillview/maps/LoadCsvFileMapper.java, platform/src/main/java/org/hillview/remoting/HillviewServer.java, platform/src/main/java/org/hillview/remoting/RemoteOperation.java, platform/src/main/proto/hillview.proto, platform/src/test/java/org/hillview/sketch/RemotingTest.java, web/src/main/java/org/hillview/InitialObjectTarget.java
Implements memoization at the servers.
Nits to the deployment scripts.
=> Implements memoization and introduces changes to the deployment scripts

platform/.idea/misc.xml, platform/platform.iml, platform/pom.xml, platform/src/main/java/org/hillview/table/EqualityFilter.java, platform/src/main/java/org/hillview/utils/TestTables.java, platform/src/test/java/org/hillview/sketch/EqualityFilterTest.java
It works for Integers and Strings now.
Let me know if I should do something differently. (Even silly things like code formatting.)
=> Equality filter map

web/src/main/webapp/dialog.ts, web/src/main/webapp/hillview.css
It now grows with the size of the contents.
=> Made dialog slimmer

platform/src/main/java/org/hillview/dataset/RemoteDataSet.java, platform/src/main/java/org/hillview/remoting/HillviewServer.java
@lalithsuresh's fix for me exceeding the message size
=> Grpc message size

web/src/main/webapp/table.ts
Now it is fast again for very wide tables as well.
=> Highlight cells

web/src/main/webapp/table.ts
=> Filtering results display on new page

platform/src/main/java/org/hillview/remoting/HillviewServer.java
Implements exception propagation.
=> Propagate server exceptions to RemoteDataSet

platform/src/main/java/org/hillview/dataset/LocalDataSet.java, platform/src/main/java/org/hillview/remoting/HillviewServer.java
This propagates throwables from the sketch/map/flatMap calls up the stack and over the wire.
=> Exception propagation

web/src/main/webapp/heatMapArray.ts, web/src/main/webapp/hillview.css, web/src/main/webapp/ui.ts, web/src/main/webapp/vis.ts
* Overlay legend is removed, but we show a fixed color legen on top, and x/y axes when the mouse hovers over a single heat map.
* Added title that displays the array dimension description.
* Added a textual indicator that show the x/y values.
* Added some semi-transparent rectangles that make the axes/indicators more readable.
* The heat map array is rendered in one big svg now. Using multiple divs wasn't possible as elements from different svgs had to be drawn on top of each other, which is way more complicated when drawing in different divs.
* Scrollbar is directly next to the heat map array now.
=> Fixed multiple heat map array issues.

web/src/main/webapp/heatMap.ts, web/src/main/webapp/heatMapArray.ts, web/src/main/webapp/hillview.css, web/src/main/webapp/histogram2d.ts, web/src/main/webapp/menu.ts, web/src/main/webapp/table.ts, web/src/main/webapp/ui.ts, web/src/main/webapp/vis.ts
The `ColorMap` and `ColorLegend` classes are now used in `HeatMap` and `HeatMapArray`. It would be nice to also use these in `Histogram2D`, but this is more challenging, as it should then also support selection in the legend.
=> Added ability to change color maps

web/src/main/webapp/heatMapArray.ts, web/src/main/webapp/hillview.css, web/src/main/webapp/vis.ts
And made the color legend context menu only appear when right-clicking the color bar, as opposed to the entire legend.
=> Added topmenu to heatmap array

platform/.idea/misc.xml, platform/src/main/java/org/hillview/dataset/api/IJson.java, platform/src/main/java/org/hillview/sketches/ExactFreqSketch.java, platform/src/main/java/org/hillview/sketches/FreqKList.java, platform/src/main/java/org/hillview/sketches/FreqKSketch.java, web/src/main/java/org/hillview/RpcTarget.java, web/src/main/java/org/hillview/TableTarget.java, web/src/main/webapp/columnConverter.ts, web/src/main/webapp/heavyhittersview.ts, web/src/main/webapp/rpc.ts, web/src/main/webapp/table.ts, web/src/main/webapp/tableData.ts
Two additions to the UI:
1. Sorted List for HeavyHitters.
2. Dialog box for HyperLogLog aka Counting distinct elements (joint with Udi).
=> Heavy hitters sorted + HyperLogLog

web/src/main/webapp/heavyhittersview.ts, web/src/main/webapp/table.ts, web/src/main/webapp/ui.ts
Code review + other small changes
=> Heavy hitters ui

web/src/main/webapp/menu.ts
That was a quicker fix than expected.
=> Hide submenus when leaving a top menu cell

web/src/main/webapp/vis.ts
I used a static counter, so the caller doesn't have to do anything extra.
=> Make the gradient ids for color legends unique

platform/src/main/java/org/hillview/sketches/RandomSamplingSketch.java, platform/src/test/java/org/hillview/test/LAMPMapTest.java, platform/src/test/java/org/hillview/test/RandomSamplingSketchTest.java, web/src/main/java/org/hillview/TableTarget.java, web/src/main/webapp/lamp.ts, web/src/main/webapp/table.ts, web/src/main/webapp/tableData.ts
* Show the LAMP operation time on the page.
* Automatically enable log scale in LAMP view.
* Deterministic sampling
* Display on the page how many numeric columns were selected
=> A few small changes for the demo

platform/src/main/java/org/hillview/table/membership/DenseMembershipSet.java, platform/src/test/java/org/hillview/test/MembershipTest.java
There was a small bug in the reservoir sampling procedure.
=> Sample dense

platform/src/main/java/org/hillview/sketches/BasicColStats.java, platform/src/main/java/org/hillview/sketches/HeatMap.java, platform/src/main/java/org/hillview/sketches/HeatMap3D.java, platform/src/main/java/org/hillview/sketches/HeatMap3DSketch.java, platform/src/main/java/org/hillview/sketches/HeatMapSketch.java, platform/src/main/java/org/hillview/sketches/Histogram.java, platform/src/main/java/org/hillview/sketches/HistogramSketch.java, platform/src/main/java/org/hillview/sketches/SampleCorrelationSketch.java, platform/src/main/java/org/hillview/table/api/IMembershipSet.java, platform/src/main/java/org/hillview/table/api/IRowIterator.java, platform/src/main/java/org/hillview/table/api/ISampledRowIterator.java, platform/src/main/java/org/hillview/table/membership/DenseMembershipSet.java, platform/src/main/java/org/hillview/table/membership/FullMembershipSet.java, platform/src/main/java/org/hillview/table/membership/NoSampleRowIterator.java, platform/src/main/java/org/hillview/table/membership/SparseMembershipSet.java, platform/src/main/java/org/hillview/utils/Randomness.java, platform/src/test/java/org/hillview/test/BasicStatSketchTest.java, platform/src/test/java/org/hillview/test/HistogramTest.java, platform/src/test/java/org/hillview/test/MembershipTest.java
Currently the 3D histogram enforces the rate
=> Smart iterator

README.md, bin/upload-data.py, deployment/config.yaml, platform/src/main/java/org/hillview/maps/CreateColumnJSMap.java, platform/src/main/java/org/hillview/storage/JsonFileLoader.java, platform/src/main/java/org/hillview/storage/TextFileLoader.java, platform/src/main/java/org/hillview/table/BaseTable.java, platform/src/main/java/org/hillview/table/columns/BaseArrayColumn.java, platform/src/test/java/org/hillview/test/JavascriptTest.java, platform/src/test/java/org/hillview/test/JsonTest.java, web/src/main/java/org/hillview/RpcServer.java, web/src/main/java/org/hillview/targets/TableTarget.java, web/src/main/webapp/dataViews/heatMapView.ts, web/src/main/webapp/dataViews/histogram2DView.ts, web/src/main/webapp/dataViews/histogramView.ts, web/src/main/webapp/dataViews/histogramViewBase.ts, web/src/main/webapp/dataViews/lampView.ts, web/src/main/webapp/index-dev.html, web/src/main/webapp/index-onecloud.html, web/src/main/webapp/index.html, web/src/main/webapp/javaBridge.ts, web/src/main/webapp/loadMenu.ts, web/src/main/webapp/package.json, web/src/main/webapp/rpc.ts, web/src/main/webapp/tableTarget.ts, web/src/main/webapp/ui/CDFPlot.ts, web/src/main/webapp/ui/histogramPlot.ts, web/src/main/webapp/ui/mouseApi.ts, web/src/main/webapp/ui/plot.ts, web/src/main/webapp/ui/plottingSurface.ts
Also, compress JSON message from browser to server.
=> Modularized histogram ui; bug-fixes

platform/src/main/java/org/hillview/sketches/MinKRows.java, platform/src/main/java/org/hillview/sketches/MinKSet.java, platform/src/main/java/org/hillview/sketches/SampleDistinctElementsSketch.java, platform/src/main/java/org/hillview/utils/TestTables.java, platform/src/test/java/org/hillview/test/MinKTest.java
Includes min and max computation in computing the sample of distinct elements.
=> String histogram

bin/delete-data.py, bin/deploy.py, bin/hillviewCommon.py, bin/run-on-all.py, bin/start.py, bin/status.py, bin/stop.py, bin/upload-data.py
=> Address the pylint warnings

bin/hillviewCommon.py, bin/stop.py
Useless object inheritance
Unnecessary "else" after "return"
Line too long
=> Useless object inheritance

bin/lib.sh
=> Add shebang in lib.sh

platform/pom.xml, web/pom.xml
https://github.com/vmware/hillview/pull/397
=> Rename dependences to dependencies

platform/src/main/java/org/hillview/storage/GenericLogs.java
=> Adding File Names in the UI

platform/src/main/java/org/hillview/main/BatchLogAnalysis.java
Modify BatchLogAnalysis to get heatmap data from nsx_manager folder and nsx_edge folder separately
=> BatchLogAnalysis separate nsx_manager and nsx_edge

web/src/main/java/org/hillview/RpcTarget.java, web/src/main/java/org/hillview/targets/TableTarget.java, web/src/main/webapp/dataViews/tsViewBase.ts, web/src/main/webapp/ui/dialog.ts
=> Improved selection boxes; fixes a couple of other bugs

web/src/main/webapp/dataViews/heavyHittersView.ts, web/src/main/webapp/dataViews/schemaView.ts, web/src/main/webapp/dataViews/tableView.ts, web/src/main/webapp/dataViews/tsViewBase.ts, web/src/main/webapp/datasetView.ts, web/src/main/webapp/initialObject.ts, web/src/main/webapp/schemaClass.ts
This also fixes a few other bugs related to renamed columns.
=> Support for converting in schema view

platform/src/main/java/org/hillview/utils/JsonList.java, platform/src/main/java/org/hillview/utils/JsonString.java, uiconfig.json, web/src/main/java/org/hillview/targets/InitialObjectTarget.java, web/src/main/webapp/dataViews/schemaView.ts, web/src/main/webapp/dataViews/tableView.ts, web/src/main/webapp/initialObject.ts, web/src/main/webapp/javaBridge.ts, web/src/main/webapp/loadMenu.ts, web/src/main/webapp/toplevel.ts
The file uiconfig.json in the root directory of hillview will control some optional features of the UI.
This enables experimental features locally.
=> Per-deployment config of UI

platform/pom.xml, web/src/main/java/org/hillview/dataStructures/DyadicDecomposition.java, web/src/main/java/org/hillview/dataStructures/HistogramRequestInfo.java, web/src/main/java/org/hillview/dataStructures/PrivateHistogram.java, web/src/main/java/org/hillview/targets/DPWrapper.java, web/src/test/java/org/hillview/HistogramAccuracyTest.java
Also accuracy benchmark.
@mbudiu-vmw ptal.
=> Bug fix for noise computation

platform/pom.xml, platform/src/main/java/org/hillview/management/ClusterConfig.java, platform/src/main/java/org/hillview/table/PrivacySchema.java, web/pom.xml, web/src/main/java/org/hillview/benchmarks/DPBenchmarks.java, web/src/main/java/org/hillview/dataStructures/PrivateHistogram.java, web/src/main/java/org/hillview/targets/DPWrapper.java
@pratiksha : I have added the ability to run benchmarks using a cloud-based dataset.
When you run DPBenchmarks you supply a list of arguments containing one or more of DP, Cloud, Local. Then it runs these benchmarks.
Unfortunately currently AWS blocks the port we are using, so to run the cloud benchmark you actually have to run it from another AWS machine. But it works, I tried it.
=> Support to run the benchmark in the cloud

platform/src/main/java/org/hillview/main/RNGBenchmarks.java, platform/src/main/java/org/hillview/security/KeyLoader.java, platform/src/main/java/org/hillview/security/PersistedKeyLoader.java, platform/src/main/java/org/hillview/security/SecureLaplace.java, platform/src/main/java/org/hillview/security/TestKeyLoader.java, platform/src/test/java/org/hillview/test/security/SecureLaplaceTest.java, web/src/main/java/org/hillview/benchmarks/DPBenchmarks.java, web/src/main/java/org/hillview/dataStructures/AugmentedHistogram.java, web/src/main/java/org/hillview/dataStructures/PrivateHistogram.java, web/src/main/java/org/hillview/targets/DPWrapper.java, web/src/test/java/org/hillview/HistogramAccuracyTest.java
This PR allows for deterministically testing with multiple different PRF keys for accuracy measurements.
=> Add custom AES key loader for tests

platform/src/main/java/org/hillview/utils/Utilities.java, web/src/main/java/org/hillview/benchmarks/DPAccuracyBenchmarks.java, web/src/main/java/org/hillview/dataStructures/PrivateHeatmapFactory.java, web/src/main/java/org/hillview/dataStructures/PrivateHistogram.java, web/src/main/java/org/hillview/utils/PrivacyUtils.java
Some refactoring and a couple of bug fixes in the noise scale computation; the order of log and product were swapped.
=> Heatmap scale

platform/src/main/java/org/hillview/utils/CountWithConfidence.java, platform/src/main/java/org/hillview/utils/Noise.java, web/src/main/java/org/hillview/dataStructures/PrivateHeatmapFactory.java, web/src/main/java/org/hillview/dataStructures/PrivateHistogram.java, web/src/main/java/org/hillview/targets/DPWrapper.java, web/src/main/java/org/hillview/utils/PrivacyUtils.java
Implements confidence intervals by sampling the CDF and computing the empirical percentiles.
=> Empirical confidence intervals

platform/src/main/java/org/hillview/storage/CassandraSSTableLoader.java, platform/src/main/java/org/hillview/storage/JdbcDatabase.java, platform/src/main/java/org/hillview/storage/OrcFileLoader.java, platform/src/main/java/org/hillview/storage/ParquetFileLoader.java, platform/src/main/java/org/hillview/table/Table.java, platform/src/main/java/org/hillview/table/api/IColumnLoader.java, platform/src/main/java/org/hillview/table/columns/LazyColumn.java, platform/src/test/java/org/hillview/test/storage/SSTableTest.java
Now the lazy loader and non-lazy loader will point to loadColumns()
=> Adding test case and remove redundant code at columns loader

platform/src/test/java/org/hillview/test/storage/SSTableTest.java
Update the sstableTest.java to reflect the latest update of yesterday's code
=> Change the return value of rowCount into long instead of int

docs/userManual.md, docs/userManual.src, platform/src/main/java/org/hillview/storage/FileSetDescription.java, web/src/main/webapp/dataViews/chartView.ts, web/src/main/webapp/dataViews/correlationHeatmapView.ts, web/src/main/webapp/dataViews/heatmapView.ts, web/src/main/webapp/dataViews/heavyHittersView.ts, web/src/main/webapp/dataViews/histogram2DView.ts, web/src/main/webapp/dataViews/histogramView.ts, web/src/main/webapp/dataViews/quartilesHistogramView.ts, web/src/main/webapp/dataViews/schemaView.ts, web/src/main/webapp/dataViews/spectrumView.ts, web/src/main/webapp/dataViews/tableView.ts, web/src/main/webapp/dataViews/trellisHeatmapView.ts, web/src/main/webapp/dataViews/trellisHistogram2DView.ts, web/src/main/webapp/dataViews/trellisHistogramQuartilesView.ts, web/src/main/webapp/dataViews/trellisHistogramView.ts, web/src/main/webapp/javaBridge.ts, web/src/main/webapp/tableTarget.ts, web/src/main/webapp/ui/dataRangeUI.ts, web/src/main/webapp/ui/heatmapLegendPlot.ts, web/src/main/webapp/ui/histogramLegendPlot.ts, web/src/main/webapp/ui/legendPlot.ts, web/src/main/webapp/ui/piePlot.ts, web/src/main/webapp/ui/scroll.ts, web/src/main/webapp/ui/ui.ts, web/src/main/webapp/util.ts
=> Highlight in heatmaps and 2d histograms

README.md
=> fix typo about checking cluster status

bin/start.py, web/src/main/webapp/datasetView.ts
Hopefully this fixes #647.
I will merge this because it fixes another bug I introduced in the last commit.
=> Fix typo in start script

web/src/main/webapp/hillview.css, web/src/main/webapp/ui/menu.ts
This PR will add a shadow to the menu and submenu.
=> Add Menu Shadow

bin/install-cassandra.sh, bin/install-dependencies.sh, bin/rebuild.sh, platform/pom.xml, platform/src/test/java/org/hillview/test/storage/SSTableTest.java
@daniarherikurniawan : this installs the correct shaded jar.
=> install correct shaded jar

platform/src/main/java/org/hillview/storage/CassandraSSTableLoader.java
@daniarherikurniawan : without this check the `testCassandraTypeConversion` test started failing on my machine. Perhaps Cassandra optimized the storage after a while?
=> Check for null cells in cassandra tables

web/src/main/webapp/util.ts
=> Fix bug in computing point on LocalDate axis

web/src/main/webapp/ui/menu.ts
=> Revert "Add sub menu container in the left side of main menu"

web/src/main/webapp/dataViews/tableView.ts, web/src/main/webapp/javaBridge.ts, web/src/main/webapp/ui/dialog.ts, web/src/main/webapp/util.ts
Three usability improvements for table views:
- menu to conceal all columns that are hidden
- context menu to move a row to the middle
- context menu to select all values around the current cell
=> Usability improvements

data/geo/airports/download.py
* Added execution permission to this file
* Removed the file name from the site variable
=> Fix error in data/geo/airports/download.py

.github/workflows/unit_tests.yml, .gitignore, bin/demo-data-cleaner.sh, bin/generate-delta-table.py, bin/install-dependencies.sh, platform/pom.xml, platform/src/main/java/org/hillview/maps/ExtractWorkerFilesMap.java, platform/src/main/java/org/hillview/storage/ParquetFileLoader.java, platform/src/main/java/org/hillview/storage/delta/DeltaTableDescription.java, platform/src/test/java/org/hillview/test/storage/DeltaTableTest.java, web/src/main/java/org/hillview/targets/InitialObjectTarget.java, web/src/main/webapp/initialObject.ts, web/src/main/webapp/javaBridge.ts, web/src/main/webapp/loadView.ts
* Implemented reading from delta table (both backend and frontend)
* Added a script for generating a test delta table (by adding a `-g` option to `demo-data-cleaner.sh`). Currently the dependencies are not installed by default.
* Added a test case for reading from delta table.
=> Implement reading from delta table

bin/hillviewCommon.py, web/src/main/java/org/hillview/targets/InitialObjectTarget.java, web/src/main/webapp/loadView.ts
* Autofill HDFS URI in DeltaTableDialog
* Use login shell to run commands on remote hostsso that that hilview processes can pick up environment variables.
=>     Autofill HDFS URI in DeltaTableDialog

bin/README.md, bin/deploy-hdfs.py, deployment/ansible.cfg, deployment/install-hdfs.yml, deployment/templates/core-site.xml.j2, deployment/templates/hdfs-site.xml.j2, deployment/templates/workers.j2
Usage: `python3 deploy-hdfs.py config.json`
=> Add scripts for setting up hdfs

platform/pom.xml, platform/src/main/java/org/hillview/main/DemoDataCleaner.java
Signed-off-by: Mihai Budiu <mbudiu@vmware.com>
=> Bump gson version
