.gitignore
This prevents the IntelliJ iml files from being tracked by git. They're being constructed based on the maven pom.xml files anyway.
=> Remove iml files from git

platform/src/main/java/org/hillview/sketches/FullCorrelationSketch.java, platform/src/test/java/org/hillview/sketch/CorrelationTest.java
The reason the test failed was that the sketch was unable to `add` two `zero`s, resulting in a `NaN` in the result. The sketch is able to cope with this now. (But it is still interesting that there are siblings that are both `zero`s.)
The result of the sketch is still non-deterministic in the sense that there are very small variations, caused by (I think) variations in floating point accuracy due to the exact order of when the different leafs of the dataset are merged, or on how the tree is structured exactly.
=> Fixed the test that was failing sometimes

web/src/main/webapp/hillview.css, web/src/main/webapp/menu.ts
The submenus now open when clicked, not when hovered over. I found this more friendly.
=> Hide the submenus on the top when action is performed.

web/src/main/java/org/hillview/TableTarget.java
The `web` project wasn't compiling, as the `FreqKList.filter()` method returns void, whereas a `FreqKList` object is expected.
=> Fix for compilation error

web/src/main/webapp/dialog.ts, web/src/main/webapp/hillview.css
It didn't work earlier (for me at least). ~~The `onkeydown` has to be set in the global `document` element, since [otherwise the escape key isn't caught](https://stackoverflow.com/q/3369593/2501474)~~.
=> Fix keyboard shortcuts in dialog

web/src/main/webapp/heatMapArray.ts, web/src/main/webapp/rpc.ts
It was caused by the fact that if you change the size repeatedly (and quickly), the z-bins (category names) where updated while the heatmaps were being drawn, resulting in the code trying to access a property of something that doesn't exist. I solved this by making the array of z-bins not a global object, but an object that goes through the request pipeline, so that it is associated to only a single HeatMap3D request, and there are no inconsistencies.
The error wasn't visible to me before, as somehow it's more prominent in Firefox. (Slower JavaScript engine, perhaps?)
I've also changed the `rpc.ts` file, as it caught this error, which made it harder to debug. The `try-catch` block was meant for the JSON parsing, but it caught errors in the drawing functions, which should not be the case, …
=> Fixed the error message on resizing the heat map array

web/src/main/webapp/hillview.css, web/src/main/webapp/table.ts, web/src/main/webapp/ui.ts, web/src/main/webapp/vis.ts
I've created a new interface, `IElement`, which is an interface for something more general than `IHtmlElement`. Perhaps `IHtmlElement` can be replaced by this new interface? The reason is that [`SVGElement`](https://developer.mozilla.org/en-US/docs/Web/API/SVGElement)s are not [`HTMLElement`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement)s, as they live in their own namespace. They *are* both [`Element`](https://developer.mozilla.org/en-US/docs/Web/API/Element)s though.
=> Made a reusable class for the position/count display

web/src/main/webapp/heatMapArray.ts, web/src/main/webapp/hillview.css, web/src/main/webapp/vis.ts
Somehow, Firefox doesn't render svg text elements according to the W3C standards.. To support all browsers, I guess it's better not to use the `alignment-baseline` property of svg `<text>` elements for now.
I also removed the redundant axis labels in the heat map array view. Now they're only visible in the rectangle that shows the values as well.
=> Fixed text alignment issues in Firefox.

web/src/main/webapp/lamp.ts
The dialog now auto-selects the LAMP columns if it is evoked from the LAMP view.
=> Fix auto select of LAMP columns for heat map array

web/src/main/webapp/hillview.css
Otherwise the axis labels aren't visible if the heatmap array is the last `FullPage`.
=> Add bottom margin for heatmap array

bin/demo-backend-start.sh, platform/src/main/java/org/hillview/sketches/HeapTopK.java, platform/src/main/java/org/hillview/sketches/ITopK.java, platform/src/main/java/org/hillview/sketches/IntTreeTopK.java, platform/src/main/java/org/hillview/sketches/NextKSketch.java, platform/src/main/java/org/hillview/sketches/TreeTopK.java, platform/src/main/java/org/hillview/table/ListComparator.java, platform/src/main/java/org/hillview/table/RecordOrder.java, platform/src/main/java/org/hillview/table/api/IDateColumn.java, platform/src/main/java/org/hillview/table/api/IDoubleColumn.java, platform/src/main/java/org/hillview/table/api/IDurationColumn.java, platform/src/main/java/org/hillview/table/api/IIntColumn.java, platform/src/main/java/org/hillview/table/api/IStringColumn.java, platform/src/main/java/org/hillview/table/api/IndexComparator.java, platform/src/main/java/org/hillview/table/columns/ObjectArrayColumn.java, platform/src/main/java/org/hillview/table/columns/SparseColumn.java, platform/src/test/java/org/hillview/test/ListComparatorTest.java, platform/src/test/java/org/hillview/test/MonoidTopKTest.java, platform/src/test/java/org/hillview/test/TreeTopKTest.java, platform/src/test/java/org/hillview/test/TreeVsHeapTest.java
Reduces allocations in the TopK implementations and NextKSketch. Given that all uses of `TreeTopK<T>` were with `TreeTopK<Integer>`, I added a specialized version `IntTreeTopK`. Allocations all in all were reduced from about 115MB -> ~600KB per TopK against 6.6M records.
=> TopK performance improvements

platform/src/test/java/org/hillview/test/RemotingTest.java, web/src/main/java/org/hillview/RpcTarget.java
This hopefully addresses the race condition around interrupts.
=> Execute frontend RPC responses on a separate threadpool

web/src/main/webapp/dataViews/histogramViewBase.ts
Will choose a number of buckets that would minimize bucketing effects. Note that this is true for all histograms. So in two dimensional histograms if one access has (say) a range of 44 and 40 is the maximum number of colors allowed, then it would choose 22 colors, each with two values.
=> Smart buckets

platform/pom.xml, web/pom.xml
Prevent the warnings while building web and platform.
=> Prevent '[WARNING] Using platform encoding (UTF-8 actually)'

platform/src/main/java/org/hillview/storage/HillviewLogs.java
=> Ignore the empty lines instead of halting with 'Could not parse line'

bin/stop.py
If the user runs the stop.py when tomcat is not running, will encounter the following exception
root@hillview-root:~/DEPLOY-HILLVIEW/hillview/bin# python3 stop.py config.json
Importing configuration from config.json
Stopping web server hillview-root
On hillview-root : /root/hillview/apache-tomcat-9.0.4/bin/shutdown.sh
Oct 03, 2018 1:35:09 AM org.apache.catalina.startup.Catalina stopServer
SEVERE: Could not contact [localhost:[8005]]. Tomcat may not be running.
Oct 03, 2018 1:35:09 AM org.apache.catalina.startup.Catalina stopServer
SEVERE: Catalina.stop:
java.net.ConnectException: Connection refused (Connection refused)
at java.net.PlainSocketImpl.socketConnect(Native Method)
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
at …
=> Handle the java.net.ConnectException: Connection refused exception

platform/src/main/java/org/hillview/utils/Utilities.java
Current:  hillview-leaf-2, ?
With Fix: hillview-leaf-2, hillview-leaf-1: hillview-leaf-1: Name or service not known
Also, dump the cause in the logs.
=> Display invalid hostname with reason instead of '?'

bin/force-gc.sh
=> Use $() notation instead of legacy backticked

platform/src/main/java/org/hillview/maps/FindFilesMapper.java
Now if atleast single worker node contains a directory it will show the output for that file and not show the  RunTimeException which was shown earlier.
=> Make the directory optional to exist in all the worker nodes

bin/delete-data.py, bin/deploy.py, bin/download-data.py, bin/hillviewCommon.py, bin/hillviewConsoleLog.py, bin/run-on-all.py, bin/start.py, bin/status.py, bin/stop.py, bin/upload-data.py
root@hillview-root:~/DEPLOY-HILLVIEW/hillview/bin# python3 start.py config.json
2018-11-02 04:14:12,085 - hillviewCommon - INFO - Reading cluster configuration from config.json
2018-11-02 04:14:12,086 - start - INFO - Starting web server hillview-root
2018-11-02 04:14:12,088 - hillviewCommon - INFO - On hillview-root: export WEB_CLUSTER_DESCRIPTOR=serverlist; cd /root/hillview; nohup apache-tomcat-9.0.4/bin/startup.sh &
Tomcat started.
2018-11-02 04:14:12,533 - start - INFO - Starting worker hillview-leaf-1
2018-11-02 04:14:12,535 - hillviewCommon - INFO - On hillview-leaf-1: cd /root/hillview/hillview; nohup java -Dlog4j.configurationFile=./log4j.properties -server  -Xmx4G -Xloggc:/root/hillview/hillview/gc.log -jar /root/hillview/hillview/hillview-server-jar-with-dependencies.jar …
=> Integrate console logging instead of simple prints

bin/lib.sh
Debian and Ubuntu are similar and, once I made this small change, the
install went fine for me on Debian.
=> install-dependencies.sh: Add support for Debian.

bin/install-dependencies.sh, data/ontime_private/gen_metadata.py, platform/src/main/java/org/hillview/table/PrivacySchema.java, web/pom.xml, web/src/main/java/org/hillview/targets/PrivateTableTarget.java, web/src/main/webapp/dataViews/heatmapView.ts, web/src/main/webapp/dataViews/histogram2DView.ts, web/src/main/webapp/dataViews/histogramView.ts, web/src/main/webapp/dataViews/schemaView.ts, web/src/main/webapp/dataViews/spectrumView.ts, web/src/main/webapp/dataViews/tableView.ts, web/src/main/webapp/dataViews/trellisHeatmapView.ts, web/src/main/webapp/dataViews/trellisHistogram2DView.ts, web/src/main/webapp/dataViews/trellisHistogramView.ts, web/src/main/webapp/datasetView.ts, web/src/main/webapp/img/jsoneditor-icons.svg, web/src/main/webapp/index.html, web/src/main/webapp/initialObject.ts, web/src/main/webapp/javaBridge.ts, web/src/main/webapp/jsoneditor.css, web/src/main/webapp/loadMenu.ts, web/src/main/webapp/package.json, web/src/main/webapp/toplevel.ts, web/src/test/java/org/hillview/PrivacySchemaTest.java
This adds additional dependencies, so one need to run ./bin/install-dependencies.sh before using it.
The "tab" of a private dataset now has a menu with an item "edit privacy policy". This shows the privacy policy as JSON; once edited all the views displayed are refreshed. @pratiksha : please take a look.
=> Use a JSON editor to edit the privacy metadata

platform/src/main/java/org/hillview/main/RNGBenchmarks.java, platform/src/main/java/org/hillview/security/SecureLaplace.java, platform/src/main/java/org/hillview/table/PrivacySchema.java, platform/src/main/java/org/hillview/utils/Utilities.java, platform/src/test/java/org/hillview/test/security/SecureLaplaceTest.java, platform/src/test/java/org/hillview/test/table/PrivacySchemaTest.java, web/src/main/java/org/hillview/benchmarks/DPBenchmarks.java, web/src/main/java/org/hillview/dataStructures/DyadicDecomposition.java, web/src/main/java/org/hillview/dataStructures/PrivateHeatmap.java, web/src/main/java/org/hillview/dataStructures/PrivateHistogram.java, web/src/main/java/org/hillview/targets/DPWrapper.java, web/src/main/java/org/hillview/targets/InitialObjectTarget.java, web/src/main/java/org/hillview/targets/PrivateFileDescriptionTarget.java, web/src/main/java/org/hillview/targets/PrivateSimpleDBTarget.java, web/src/main/java/org/hillview/targets/PrivateTableTarget.java, web/src/main/webapp/datasetView.ts, web/src/test/java/org/hillview/HistogramAccuracyTest.java
Adds a "save" button to persist an edited privacy schema, and refactors the secure sampling implementation to generate a new key or read one from file.
=> Facilities for saving schema and private key

bin/hillview-start.bat
On Windows (at least without WLS), its catalina.bat instead of .sh. Also set CATALINA_HOME since tomcat guessing it didn't work for some reason.
=> fixed tomcat start on Windows

platform/pom.xml, platform/src/main/java/org/hillview/maps/CreateColumnJSMap.java, platform/src/main/java/org/hillview/table/rows/JSVirtualRowSnapshot.java, platform/src/test/java/org/hillview/test/JavascriptTest.java
Nashorn has been deprecated as of JDK 11, and will not be available at all from JDK 15 onwards: https://openjdk.java.net/jeps/372. This patch migrates our Nashorn-based code to use GraalJS
instead.
It should run on stock JDKs, including JDK 8 (I tested it with JDK 12). The JS will be interpreted on top of the JVM, as I believe was also the case with Nashorn. It should benefit from GraalVM's JIT if users run Hillview using the GraalJDK instead.
I haven't E2E tested this yet from a browser, so please try it out before you merge. It passes all the tests that used to be in `JavascriptNashornTest` (now renamed to `JavascriptTest`).
=> Migrate from Nashorn to GraalJS

README.md
I've added the instructions on setting up VS Code in the README. It includes a step-by-step guide to add the necessary extensions, run Maven commands, and attach a debugger.
Here is the screenshot of what I wrote in the markdown format.
=> Adding instruction on setting up vscode in the README

web/src/main/webapp/initialObject.ts, web/src/main/webapp/loadView.ts
Originally, the federated menu won't load, due this logic:
```
const connection = dialog.getCassandraConnection();
if (connection == null) {
this.page.reportError("Not a valid connection");
return;
}
```
The `dialog.getCassandraConnection()` will always return `null`, thus it displays  `Not a valid connection`. This `getCassandraConnection()` will be executed when the user presses the `confirm` button. Therefore, I remove the null checking, and make it similar to ` getJdbcConnection()`.
In the next PR, I will add Hive connection dialog on top of this logic.
=> Fix the problem on loading Federated Menu

web/src/main/webapp/ui/menu.ts
This PR will handle the case where the submenu must be displayed on the left side of the main menu. It is done by adding an empty submenu container on the left of the main menu. When there is not enough room to display the submenu on the right, the submenu will be placed into the container. The container will copy all attributes of the current submenus that need to be displayed. When hiding the submenu, all attributes will be reset and the user won't be able to notice that there are empty containers on the left of the main menu.
=> Add sub menu container in the left side of main menu

bin/install-cassandra.sh
The old url is a temporary download link. We should've used this one since the beginning. This download endpoint provides any version of Cassandra.
=> Fix Cassandra Download Link

bin/install-dependencies.sh
`json` is a built-in python module and can't to be installed via `pip`.
=> Remove erroneous pip install command

data/ontime/download.py, platform/pom.xml
* Update `jblas` to 1.2.5
The 1.2.4 version doesn't work with `libgfortran5` on ubuntu 20.04.
* Use `-no-check-certificate` option with `wget` when downloading the on time data
Without this option `wget` will fail with the error message "Unable to locally verify the issuer's authority."
=> Fix error when building and testing on Ubuntu 20.04

.github/workflows/unit_tests.yml, bin/install-dependencies.sh, data/ontime/download.py
* Add GitHub action for unit tests
* Add `-y` flag to install command so no interaction is needed
* Implement a workaround for the problem that the ip range used for GitHub actions seem to have been blocked by bts.gov: if GitHub action environment is detected, download from internet archive instead.
=> Add github action for unit tests

bin/lib.sh, bin/rebuild.sh
* Converted all indents in `lib.sh` to spaces (used to be a mix of spaces and tabs).
* There is no need to source `lib.sh` in `rebuild.sh`, removed
=> Reformat scripts

bin/deploy.py
* `hillview-aggregator-manager.sh` uses `forever.sh` but was not deployed
* `hillview-aggregator-manager.sh` assumes `hillview-server-jar-with-dependencies.jar` is at the root of service directory, but it's actually deployed to `service_directory/hillview/` is a node is only an aggregator but not a worker.
=> Fix bug in deploy.py

platform/pom.xml
The built-in rule is named `dependencyConvergence` rather than `dependencyConverge`.
Currently run `mvn enforcer:enforce` doesn't do anything, while after this patch it can show all the dependency conflicts.
Reference:
https://maven.apache.org/enforcer/enforcer-rules/dependencyConvergence.html
=> Fix typo in platform/pom.xml

platform/src/main/java/org/hillview/sketches/BasicColStatSketch.java, platform/src/main/java/org/hillview/sketches/HLogLogSketch.java, platform/src/test/java/org/hillview/test/dataset/BasicStatSketchTest.java, platform/src/test/java/org/hillview/test/dataset/HistPerfTest.java, platform/src/test/java/org/hillview/test/dataset/HyperLogLogTest.java, platform/src/test/java/org/hillview/test/dataset/LinearProjectionTest.java, platform/src/test/java/org/hillview/test/dataset/PCATest.java, web/src/main/java/org/hillview/targets/TableTarget.java, web/src/main/webapp/dataViews/schemaView.ts, web/src/main/webapp/tableTarget.ts
Added distinct count to basic column stats. Implemented both backend and frontend.
The main change is that the signature of `BasicColStatSketch` is changed from `TableSketch<JsonList<BasicColStats>>` to `TableSketch<JsonList<Pair<BasicColStats, HLogLog>>>`
screenshot:
Resolves #708
=> Add distinct count to basic column stats

platform/src/main/java/org/hillview/sketches/BasicColStatSketch.java, platform/src/test/java/org/hillview/test/dataset/PCATest.java, web/src/main/java/org/hillview/targets/TableTarget.java, web/src/main/webapp/tableTarget.ts
Use the same seed for all columns instead of using a different seed for each column.
=> Use the same seed when estimating distint count

platform/src/test/java/org/hillview/test/storage/DeltaTableTest.java
Since generate a delta table is optional in `demo-data-cleaner.sh`, the `DeltaTableTest` shouldn't fail if a delta table is not found.
=> Skip DeltaTableTest if a table is not found

.github/workflows/unit_tests.yml, .gitignore, bin/demo-data-cleaner.sh, platform/pom.xml, platform/src/main/java/org/hillview/main/DemoDataCleaner.java, platform/src/main/java/org/hillview/storage/ParquetFileLoader.java, platform/src/main/java/org/hillview/storage/ParquetFileWriter.java, platform/src/main/java/org/hillview/table/columns/DoubleArrayColumn.java, platform/src/main/java/org/hillview/utils/Converters.java, platform/src/test/java/org/hillview/test/TestUtil.java, platform/src/test/java/org/hillview/test/storage/ParquetTest.java
* Implement `ParquetFileWriter` that can write an `ITable` to a `.parquet` file.
* Generate test parquet files in `DemoDataCleaner` (closes #346).
* Modified `ParquetTest` to use the generated parquet file.
=> Implement writing table to parquet
